export type IconType =
  | '24-support'
  | 'Cursor'
  | 'Level'
  | 'Pointing Hand'
  | 'add'
  | 'affiliate'
  | 'arrow-down'
  | 'arrow-left-1'
  | 'arrow-left'
  | 'arrow-right-1'
  | 'arrow-right'
  | 'arrow=up'
  | 'calendar'
  | 'caret_down'
  | 'chart-b'
  | 'check'
  | 'close-default'
  | 'close-thin'
  | 'copy'
  | 'danger'
  | 'down arrow'
  | 'drag'
  | 'edit'
  | 'email'
  | 'explore content'
  | 'eye-slash'
  | 'eye'
  | 'filter-1'
  | 'filter'
  | 'flash-circle'
  | 'folder'
  | 'heart-circle'
  | 'home'
  | 'import words'
  | 'info-circle'
  | 'keyboard'
  | 'lock'
  | 'logout'
  | 'maximize'
  | 'menu'
  | 'more'
  | 'move to'
  | 'next'
  | 'note'
  | 'notification'
  | 'pause'
  | 'pause1'
  | 'payment card'
  | 'payment'
  | 'play'
  | 'playing'
  | 'previous'
  | 'repeat'
  | 'repeate-music'
  | 'repeate-one'
  | 'search'
  | 'security-card'
  | 'setting'
  | 'sign in'
  | 'sign up'
  | 'slash'
  | 'smallcaps'
  | 'study'
  | 'surprise box'
  | 'tariff'
  | 'tick-circle'
  | 'translate'
  | 'trash'
  | 'upper arrow'
  | 'user'
  | 'video-play'
  | 'volume high'
  | 'volume-cross'
  | 'volume-high'
  | 'volume-low'
  | 'word list'
  | 'amex'
  | 'diners'
  | 'mastercard'
  | 'visa';
